### ISSUE TITLE
hardware

### ISSUE THREAD

**Issue by ghost** [ngerakines/auroraops#1]
did you just get the starter pack ?

https://www.amazon.de/nanoleaf-NL22-0002TW-9PK-Light-Panels-Lichtpanels/dp/B01M0W7NIP/ref=lp_7465101031_1_1

Or maybe you needed some controller to be able to interact with it ?

**Comment by ngerakines** [comment]
I have a "Starter" and "Expansion" for a total of 12 panes. As long as you have the controller/power cord that comes with the starter kit, you should be fine.

**Comment by ghost** [comment]
thanks you
